### ISSUE TITLE
Decide how we feel about FrozenStringLiteral

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/styleguide#33]
This cop checks that, in ruby 2.3. you've opted-in to frozen string literals via a pragma comment at the top of the file (it can also auto-add it).

Frozen strings will be default in 3.0 so adding this pragma now forces you to write your code accordingly and not run into issues when you upgrade.

We should decide if we want to add the pragmas to our 2.3 codebase, or ignore this check in our default rubocop config.

http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment

**Comment by GordonDiggs** [comment]
I'm :-1: on adding a comment to the top of every file

**Comment by pbrisbin** [comment]
I agree. :+1: on frozen strings, but I can wait for 3.0 instead of using a pragma now.

**Comment by dblandin** [comment]
Looks like this is okay to close since we've decided to wait until our ruby 3.0 upgrade to address this change.
