### ISSUE TITLE
Regarding your RSpec styleguide: Why do you avoid `described_class`, `let` and `subject`?

### ISSUE THREAD

**Issue by 5minpause** [codeclimate/styleguide#47]
Hi,

I was reading your Ruby/RSpec styleguide and stumbled upon these lines:

> Avoid `described_class`
> Avoid `let`, and `subject` (prefer factory methods)

Sadly I did not find any explanation why you chose to avoid these. Could you give me an idea?

Thank you.

**Comment by wfleming** [comment]
Hi @5minpause,

This blog post from Thoughtbot is a good summary of the reasons we internally avoid those methods: https://robots.thoughtbot.com/lets-not. In short, we think avoiding them leads to more explicit & clearer tests with less "magic".

These are just our internal preferences that we try to stick to. We're not saying that all teams should use these guidelines, just that these are the guidelines we've found work for us.

Thanks for your question!
